### ISSUE TITLE
RAGBase起動時のエラー

### ISSUE THREAD

**Issue by fukuda-bci** [ailab-juas/LifeCopilot#1]
おそらくIssueを分けたほうがいいが、一旦まとめて総覧する。

```
Traceback (most recent call last): File "/usr/local/src/myscripts/OpenAI_Queries.py", line 42, in check_deployment llm_helper.translator.translate("This is a test", "it") File "/usr/local/src/myscripts/utilities/translator.py", line 34, in translate request = requests.post(self.detect_endpoint, params=params, headers=headers, json=body) File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 573, in request prep = self.prepare_request(req) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request p.prepare( File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 368, in prepare self.prepare_url(url, params) File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 439, in prepare_url raise MissingSchema( requests.exceptions.MissingSchema: Invalid URL '/detect?api-version=3.0': No scheme supplied. Perhaps you meant https:///detect?api-version=3.0?
```

**Comment by fukuda-bci** [comment]
```
LLM is not working.
Please check you have a deployment name text-davinci-003 in your Azure OpenAI resource https://sknaoai-je.openai.azure.com/.
If you are using an Instructions based deployment (text-davinci-003), please check you have an environment variable OPENAI_DEPLOYMENT_TYPE=Text or delete the environment variable OPENAI_DEPLOYMENT_TYPE.
If you are using a Chat based deployment (gpt-35-turbo or gpt-4-32k or gpt-4), please check you have an environment variable OPENAI_DEPLOYMENT_TYPE=Chat.
Then restart your application.
```
このエラーは`.env`の
`OPENAI_DEPLOYMENT_TYPE=Text`
を
`OPENAI_DEPLOYMENT_TYPE=Chat`
に変更すると解消された。

**Comment by fukuda-bci** [comment]
```
Translation model is not working.
Please check your Azure Translator key in the App Settings.
Then restart your application.
```
↑このエラーはazure translattion serviceを立ち上げて接続設定をすることで解消された。
